### ISSUE TITLE
Bug: import Error due to statsmodels' Appender

### ISSUE THREAD

**Issue by mtchem** [WinVector/pyvtreat#14] opened 2020-03-09 20:35 UTC
Hello, 

I am experiencing the following error when importing pyvtreat

`---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-26-27afc19cdbfe> in <module>
      2 import pandas as pd
      3 import numpy as np
----> 4 import vtreat
      5 import vtreat.util
      6 import wvpy.util

~/anaconda3/envs/python3/lib/python3.6/site-packages/vtreat/__init__.py in <module>
      5 import numpy
      6 
----> 7 from vtreat.vtreat_api import *
      8 
      9 __docformat__ = "restructuredtext"

~/anaconda3/envs/python3/lib/python3.6/site-packages/vtreat/vtreat_api.py in <module>
      4 import numpy
      5 
----> 6 import vtreat.vtreat_impl as vtreat_impl
      7 import vtreat.util
      8 import vtreat.cross_plan

~/anaconda3/envs/python3/lib/python3.6/site-packages/vtreat/vtreat_impl.py in <module>
     13 import pandas
     14 
---> 15 import vtreat.util
     16 import vtreat.transform
     17 

~/anaconda3/envs/python3/lib/python3.6/site-packages/vtreat/util.py in <module>
     16 with warnings.catch_warnings():
     17     warnings.filterwarnings("ignore", category=DeprecationWarning)
---> 18     import statsmodels.api
     19     import statsmodels.formula.api
     20 

~/anaconda3/envs/python3/lib/python3.6/site-packages/statsmodels/api.py in <module>
     18 from . import robust
     19 from .robust.robust_linear_model import RLM
---> 20 from .discrete.discrete_model import (Poisson, Logit, Probit,
     21                                       MNLogit, NegativeBinomial,
     22                                       GeneralizedPoisson,

~/anaconda3/envs/python3/lib/python3.6/site-packages/statsmodels/discrete/discrete_model.py in <module>
     26 from scipy.stats import nbinom
     27 
---> 28 from statsmodels.compat.pandas import Appender
     29 
     30 import statsmodels.tools.tools as tools

ImportError: cannot import name 'Appender'`

I looked at SciPy's issues, and it seems like multiple packages are having issues with  importing Appender, but SciPy has closed all of those issues  without changing their package.  I've also tried using different versions of Pandas(0.23.0 - 1.0.1) and that didn't do anything.  Scipy seems to suggest using 
`from pandas.util._decorators import Appender` 

I really like vtreat, so any help/suggestions on how to import it would be appreciated. 
Thanks!

**Comment by JohnMount** [comment] 2020-03-09 20:56
Sorry you are having problems, and thanks for taking the time to research the root cause so well.  I just recently added the statsmodels dependence to vtreat to help estimate confidence the R-squared significance.  I'll look into how to remove that dependence today.  After I make that fix things should be fixed.  I'll close the issue at that time.  If that does not fix it for you, please re-open the issue.

**Comment by JohnMount** [comment] 2020-03-10 02:03
I've switched the significance calculations away from `statsmodels` to `scipy` plus `sklearn`.  Please let me know if the new release `0.4.2` works for you.  If not, please re-open the issue.

**Closed by JohnMount** 2020-03-10 02:03 UTC

**Comment by mtchem** [comment] 2020-03-10 16:58
Everything works great!

**Comment by JohnMount** [comment] 2020-03-10 17:31
That is great news. Sorry about the trouble, and thanks for checking back in that it is working.  I have released a slightly newer vtreat with hardens and checks the paths around this fix a bit more.
